import numpy as np
import pandas as pd
import logging
from backend.db import SessionLocal
from backend.models import Decision, DailyEquity
from sqlalchemy import func

logger = logging.getLogger("MonteCarlo")

def run_monte_carlo(iterations=1000):
    """
    Takes the actual historical returns generated by the bot and 
    shuffles them into 1,000 different timelines.
    Calculates the 'Risk of Ruin' and 'Average Performance' across universes.
    """
    db = SessionLocal()
    try:
        # 1. Fetch historical daily returns from Decisions/Equity
        # We'll use rewards from decisions as our return stream
        decisions = db.query(Decision).order_by(Decision.timestamp).all()
        
        if not decisions:
            print("No trade history found. Run a backtest first.")
            return

        daily_rewards = [d.reward for d in decisions if d.reward is not None]
        initial_equity = 100000.0
        
        print(f" Analyzing {len(daily_rewards)} days of returns across {iterations} universes...")

        final_equities = []
        ruined_count = 0
        
        for _ in range(iterations):
            # Shuffle the returns (This breaks the specific historical timeline)
            shuffled = np.random.choice(daily_rewards, size=len(daily_rewards), replace=True)
            
            universe_equity = initial_equity
            for ret in shuffled:
                universe_equity += ret
                if universe_equity <= 0:
                    ruined_count += 1
                    universe_equity = 0
                    break
            
            final_equities.append(universe_equity)

        # 2. Results Analysis
        final_equities = np.array(final_equities)
        avg_equity = np.mean(final_equities)
        median_equity = np.median(final_equities)
        win_rate_universes = (final_equities > initial_equity).mean() * 100
        
        print("\n--- MONTE CARLO SURVIVABILITY REPORT ---")
        print(f"Universe Iterations: {iterations}")
        print(f"Average Final Equity: ${avg_equity:,.2f}")
        print(f"Median Final Equity: ${median_equity:,.2f}")
        print(f"Probability of Profit: {win_rate_universes:.1f}%")
        print(f"Risk of Ruin (0$): {(ruined_count/iterations)*100:.1f}%")
        print("----------------------------------------\n")

        if win_rate_universes > 80:
            print(" ROBUST: The strategy succeeds in most parallel universes.")
        elif win_rate_universes > 50:
            print(" CAUTION: Performance is highly dependent on return sequencing.")
        else:
            print(" OVERFITTED: Strategy fails in the majority of random timelines.")

    finally:
        db.close()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run_monte_carlo()
