"""initial schema

Revision ID: 075ff1519165
Revises: 
Create Date: 2026-04-13 13:47:25.405133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075ff1519165'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandit_state',
    sa.Column('param_key', sa.String(), nullable=False),
    sa.Column('trials', sa.Integer(), nullable=True),
    sa.Column('total_reward', sa.Float(), nullable=True),
    sa.Column('avg_reward', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('param_key')
    )
    op.create_index(op.f('ix_bandit_state_param_key'), 'bandit_state', ['param_key'], unique=False)
    op.create_table('daily_equity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('drawdown_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_equity_id'), 'daily_equity', ['id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('params_used', sa.JSON(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('alpaca_id', sa.String(), nullable=True),
    sa.Column('parent_order_id', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_alpaca_id'), 'orders', ['alpaca_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_parent_order_id'), 'orders', ['parent_order_id'], unique=False)
    op.create_index(op.f('ix_orders_run_id'), 'orders', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_run_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_parent_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_alpaca_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_daily_equity_id'), table_name='daily_equity')
    op.drop_table('daily_equity')
    op.drop_index(op.f('ix_bandit_state_param_key'), table_name='bandit_state')
    op.drop_table('bandit_state')
    # ### end Alembic commands ###
